version: '2'
services:
    application:
        hostname: symfony-container
        image: fleporcq/symfony:3.0
        build: ./docker/symfony/
        ports:
            - 81:80
        volumes:
            - .:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini
            - ./vhost.conf:/etc/apache2/sites-enabled/vhost.conf
        user: me
        links:
            - database

    database:
        image: mysql:5.7
        ports:
            - 3307:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 82:80
        links:
            - database
        environment:
            - PMA_HOST=database
